version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results


jobs:
  build:
    
    working_directory: ~/PetClinic

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/mariadb:10.4.8

    steps:

      - checkout

      - restore_cache:
          key: PetClinic-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: PetClinic-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar